# Generated by Django 3.2.13 on 2022-07-16 18:31

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chapter_no', models.PositiveIntegerField(default=0, unique=True)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(choices=[(1, 'Boring'), (2, 'Normal'), (3, 'Biased'), (4, 'Somewhat Interesting'), (5, 'Interesting')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chapter_no'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
                ('commentor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='_api_profile_followers_+', to='api.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='_api_profile_following_+', to='api.Profile')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(None, ''), ('UPG', 'Upcoming'), ('ONG', 'Ongoing'), ('STP', 'Stopped'), ('CPD', 'Completed'), ('MPL', 'Most Popular'), ('LTS', 'Latest Release'), ('HOT', 'Hot Novel')], default='UPG', max_length=3)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('genre', models.CharField(choices=[('None', ''), ('Fiction', (('AAC', 'Action and adventure'), ('ALH', 'Alternate history'), ('ANT', 'Anthology'), ('CHL', 'Chick lit'), ('CHD', "CHILDREN'S"), ('CLS', 'Classic'))), ('Non Fiction', (('ARC', 'Art/architecture'), ('AUB', 'Autobiography')))], default='CHD', max_length=3)),
                ('alt_names', models.CharField(max_length=300, null=True)),
                ('source', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CommentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.novel'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('chapter_no', 'novel_id'), name='unique_chapter_in_novel'),
        ),
    ]
