# Generated by Django 3.2.13 on 2022-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220714_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='likes',
            field=models.IntegerField(choices=[(1, 'Boring'), (2, 'Normal'), (3, 'Biased'), (4, 'Somewhat Interesting'), (5, 'Interesting')], default=0),
        ),
    ]
