# Generated by Django 3.2.13 on 2022-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220714_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
