# Generated by Django 3.2.13 on 2022-07-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220721_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter', unique=True),
        ),
    ]
