# Generated by Django 3.2.13 on 2022-07-21 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.chapter'),
        ),
    ]
