# Generated by Django 3.2.13 on 2022-07-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chapter_ch_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['chapter']},
        ),
        migrations.AlterField(
            model_name='like',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('chapter', 'user'), name='unique_like_for_user_for_like'),
        ),
    ]
