# Generated by Django 3.2.13 on 2022-07-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220729_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='created',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='following',
            name='created',
        ),
        migrations.RemoveField(
            model_name='following',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='following',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='following',
            name='updated',
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.profile'),
        ),
    ]
